{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"snowball_output\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "calendar": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendar"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "calendar": {
                      "State": "Generated"
                    }
                  },
                  {
                    "almanac": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "datebook": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "agenda": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "logbook": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "diary": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "schedule": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "timetable": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "calendar.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendar",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "calendar.date.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendar",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "calendar.date.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendar",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "calendar.date.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendar",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "calendar.date.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendar",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "calendar.date.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendar",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "calendar.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Calendar",
                    "ConceptualProperty": "Year"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "snowball_output": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball output": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball_output": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "output": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "snowball production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "snowball productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "snowball yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.bop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "bop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "bop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.cross_sell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "cross_sell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cross sell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "cross_sell": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "sell": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "symbol sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "mark sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "sign sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "snowball_output.customer_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "snowball_output.customer_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.downsell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "downsell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "downsell": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "snowball_output.eop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "eop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "eop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "eop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.grr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "grr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "grr": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "snowball_output.measure_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "MeasureName"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "measure name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "MeasureName": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "measure": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "measure nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "measure title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "measure label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "measure tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "degree": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "quota": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "portion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "ration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "size": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "Sum of Existing": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "snowball_output.month_roll": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month_roll": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "roll": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "mth roll": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "month reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.new_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "new_customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "new_customer": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "new client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "snowball_output.nrr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "nrr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nrr": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "snowball_output.period_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "period_type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "period type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "period_type": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "period category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period brand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "period class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "snowball_output.product_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "snowball_output.product_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.snowball_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "snowball_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "essential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "snowball solution": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball explanation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball basis": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  }
                ]
              },
              "snowball_output.upsell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "upsell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "upsell": {
                      "State": "Generated"
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "calendar_date_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.date.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "calendar.date"
                      }
                    },
                    "ID": "dates_have_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar.date": {
                    "Target": {
                      "Entity": "calendar.date"
                    }
                  },
                  "calendar.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "calendar.date.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_date_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.date.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "calendar.date.variation.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "calendar.date.variation.date_hierarchy"
                    }
                  },
                  "calendar.date.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "calendar.date.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_date_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.date.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "calendar.date.variation.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "calendar.date.variation.date_hierarchy"
                    }
                  },
                  "calendar.date.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "calendar.date.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_date_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.date.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "calendar.date.variation.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "calendar.date.variation.date_hierarchy"
                    }
                  },
                  "calendar.date.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "calendar.date.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_date_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.date.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "calendar.date.variation.date_hierarchy"
                      }
                    },
                    "ID": "date_hierarchies_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar.date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "calendar.date.variation.date_hierarchy"
                    }
                  },
                  "calendar.date.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "calendar.date.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_has_date": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.date"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "calendar.date": {
                    "Target": {
                      "Entity": "calendar.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_has_day_name": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.day_name"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_day_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "calendar.day_name": {
                    "Target": {
                      "Entity": "calendar.day_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_has_day_of_week": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.day_of_week"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_day_of_week",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "calendar.day_of_week": {
                    "Target": {
                      "Entity": "calendar.day_of_week"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_has_month_name": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.month_name"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_month_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "calendar.month_name": {
                    "Target": {
                      "Entity": "calendar.month_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_has_month_number": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.month_number"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_month_numbers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "calendar.month_number": {
                    "Target": {
                      "Entity": "calendar.month_number"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.quarter"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "calendar.quarter": {
                    "Target": {
                      "Entity": "calendar.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_has_week_number": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.week_number"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_week_numbers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "calendar.week_number": {
                    "Target": {
                      "Entity": "calendar.week_number"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_has_year": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.year"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "calendar.year": {
                    "Target": {
                      "Entity": "calendar.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "calendar_has_yearmonth": {
                "Binding": {
                  "ConceptualEntity": "Calendar"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar.yearmonth"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_yearmonths",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "calendar.yearmonth": {
                    "Target": {
                      "Entity": "calendar.yearmonth"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_bop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.bop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_bop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.bop_arr": {
                    "Target": {
                      "Entity": "snowball_output.bop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_calendar": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_calendars",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_snowball_outputs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_cross_sell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.cross_sell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_cross_sell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.cross_sell": {
                    "Target": {
                      "Entity": "snowball_output.cross_sell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.customer_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customer_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.customer_churn": {
                    "Target": {
                      "Entity": "snowball_output.customer_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.customer_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customer_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.customer_key": {
                    "Target": {
                      "Entity": "snowball_output.customer_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_downsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.downsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_downsells",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.downsell": {
                    "Target": {
                      "Entity": "snowball_output.downsell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_eop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.eop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_eop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.eop_arr": {
                    "Target": {
                      "Entity": "snowball_output.eop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_grr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.grr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_grrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.grr": {
                    "Target": {
                      "Entity": "snowball_output.grr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_measure_name": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.measure_name"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_measure_name",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.measure_name": {
                    "Target": {
                      "Entity": "snowball_output.measure_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_month_roll": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_month_rolls",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.month_roll": {
                    "Target": {
                      "Entity": "snowball_output.month_roll"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_new_customer": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.new_customer"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_new_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.new_customer": {
                    "Target": {
                      "Entity": "snowball_output.new_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_nrr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.nrr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_nrrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.nrr": {
                    "Target": {
                      "Entity": "snowball_output.nrr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_period_type": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.period_type"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_period_types",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.period_type": {
                    "Target": {
                      "Entity": "snowball_output.period_type"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_churn": {
                    "Target": {
                      "Entity": "snowball_output.product_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_key": {
                    "Target": {
                      "Entity": "snowball_output.product_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_snowball_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.snowball_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_snowball_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.snowball_key": {
                    "Target": {
                      "Entity": "snowball_output.snowball_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_upsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.upsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_upsell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.upsell": {
                    "Target": {
                      "Entity": "snowball_output.upsell"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "9b0b82de-7dc6-42a6-90e2-53826b01a06d",
        "fromColumn": "month_roll",
        "fromTable": "snowball_output",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2a7574a0-7be7-40b5-a9f8-174db5a82dd5"
      },
      {
        "name": "ebd77de9-b8fc-4cfb-bd57-4932dc511de6",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7d85d6a6-0015-4fa3-b1a9-faf8adb8e469"
      },
      {
        "name": "29e4cac5-a74c-4855-abec-5bf31d28e18e",
        "fromColumn": "EOW - Saturday",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f9d24481-c760-4503-9a10-5941e087c86a"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "snowball_output",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "snowball_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e77d0c04-9d30-42f0-91d7-c2102bd3584d",
            "sourceColumn": "snowball_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9459fc8-d447-4652-b919-c654740bedec",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "product_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "871aca5f-a3e3-4e9e-be99-c35510b53beb",
            "sourceColumn": "product_key",
            "summarizeBy": "none"
          },
          {
            "name": "month_roll",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e239e6fd-d2f8-4466-838c-1bfb77abcc79",
            "sourceColumn": "month_roll",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2a7574a0-7be7-40b5-a9f8-174db5a82dd5"
                },
                "isDefault": true,
                "relationship": "9b0b82de-7dc6-42a6-90e2-53826b01a06d"
              }
            ]
          },
          {
            "name": "period_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd6ac589-e545-482f-83ba-0ad84ee62598",
            "sourceColumn": "period_type",
            "summarizeBy": "none"
          },
          {
            "name": "bop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dd705518-5b31-467d-9c03-66898c746215",
            "sourceColumn": "bop_arr",
            "summarizeBy": "sum"
          },
          {
            "name": "customer_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "85df3e8a-9ff6-4b58-82be-287010c3f6e1",
            "sourceColumn": "customer_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "product_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f19337e3-0b6d-4700-a206-a62cb5a7bae5",
            "sourceColumn": "product_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "downsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3533865c-feb7-48fd-8e03-567a2cf83067",
            "sourceColumn": "downsell",
            "summarizeBy": "sum"
          },
          {
            "name": "grr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a95529bd-49b6-49b8-b659-b33648f6e6b1",
            "sourceColumn": "grr",
            "summarizeBy": "sum"
          },
          {
            "name": "upsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2720cba0-8b94-4041-abcf-757b4e4a36dd",
            "sourceColumn": "upsell",
            "summarizeBy": "sum"
          },
          {
            "name": "cross_sell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ffcbbe09-b3d3-4efd-b790-860bb5553e00",
            "sourceColumn": "cross_sell",
            "summarizeBy": "sum"
          },
          {
            "name": "nrr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "59dca7d1-8a96-4b1b-8a48-83584d2c5faa",
            "sourceColumn": "nrr",
            "summarizeBy": "sum"
          },
          {
            "name": "new_customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e3bd7d6f-d65f-4dc0-a852-2312878a1b34",
            "sourceColumn": "new_customer",
            "summarizeBy": "sum"
          },
          {
            "name": "eop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d68c897f-b7c3-48d2-82be-e0e209aecc09",
            "sourceColumn": "eop_arr",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d3d25a7f-839f-4bb0-9562-7ba2087a062e",
        "measures": [
          {
            "name": "MeasureName",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('snowball_output'[cross_sell]) + SUM('snowball_output'[upsell])",
            "lineageTag": "d113c1cc-b77f-4bb6-abe6-27b4419c59e7"
          }
        ],
        "partitions": [
          {
            "name": "snowball_output",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\AkhilKumar\\Downloads\\snowball_output.csv\"),[Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"snowball_key\", type text}, {\"customer_key\", type text}, {\"product_key\", type text}, {\"month_roll\", type date}, {\"period_type\", type text}, {\"bop_arr\", type number}, {\"customer_churn\", type number}, {\"product_churn\", type number}, {\"downsell\", type number}, {\"grr\", type number}, {\"upsell\", type number}, {\"cross_sell\", Int64.Type}, {\"nrr\", type number}, {\"new_customer\", type number}, {\"eop_arr\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_1dc6d548-4430-4619-92af-fd78015aebc4",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ab3c0f29-43a9-4f4b-a780-46bc7ffb1491",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ec447481-6132-49bd-ac30-ed74658bbbc7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fe3c9f43-cdd0-4e2e-b91c-4282d69f75d9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "31d41eea-0438-438a-9e21-3960a459648b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8e046df8-386f-4836-91aa-a855d36f2acf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c7edec57-387c-4aa9-904a-4e3583b23ba9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cd42931b-16e0-47ac-95f0-cce5bf372e31",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "95ad3c26-a087-4312-9fd2-965b4b0195e9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1c690517-05ef-4fbd-a501-0b08456d90a0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8324a854-42c1-494a-83f2-619753575d9d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "02c55b62-232a-44e0-8103-e04c65d8b69a",
                "ordinal": 3
              }
            ],
            "lineageTag": "7838007b-b273-406f-ad79-76c64c79bbd4"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "17c791f8-2a34-4518-8455-6eafc642a639",
        "partitions": [
          {
            "name": "DateTableTemplate_1dc6d548-4430-4619-92af-fd78015aebc4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ba4e760c560446c7bbdb6a7bd014f927"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0c3229f2-40a4-4ec7-b9fe-210de488ae0b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7d85d6a6-0015-4fa3-b1a9-faf8adb8e469"
                },
                "isDefault": true,
                "relationship": "ebd77de9-b8fc-4cfb-bd57-4932dc511de6"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "88feca5b-b00a-46c6-9a04-6ca119d98aa4",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateAsInteger",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8e69f902-a5ed-4daa-948d-ba0bc6681e4f",
            "sourceColumn": "[DateAsInteger]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year less 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c615464b-7d0a-4a4e-b861-483accf928e5",
            "sourceColumn": "[Year less 1]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "212322cf-509f-4f53-a528-cd070e3ad610",
            "sourceColumn": "[MonthYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "QuarterYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "12ec421e-4999-499d-99c5-60f3b849ac65",
            "sourceColumn": "[QuarterYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bfffe279-3e2b-461e-bf6a-67548fe8cda4",
            "sourceColumn": "[MonthNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8ca4c920-c9a6-4235-b922-052ac722e382",
            "sourceColumn": "[MonthText]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4545242d-d729-4007-9294-4fe4110a3109",
            "sourceColumn": "[YearMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YMInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a65b620c-0d27-42e7-ac6c-f543ce13837b",
            "sourceColumn": "[YMInt]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekdayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dd239496-4aa5-46ed-8119-886c78735065",
            "sourceColumn": "[WeekdayNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year & Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c2e8ef4a-37c1-48c4-a9b8-105352b734f1",
            "sourceColumn": "[Year & Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c005143e-28e7-4ea6-a8d8-d682c83c10b1",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c711eae4-28cc-4394-a3e9-6bd270c4bafc",
            "sourceColumn": "[WeekNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "EOW - Saturday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ea614502-eddf-4c42-b9a8-37935fcdf4c7",
            "sourceColumn": "[EOW - Saturday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f9d24481-c760-4503-9a10-5941e087c86a"
                },
                "isDefault": true,
                "relationship": "29e4cac5-a74c-4855-abec-5bf31d28e18e"
              }
            ]
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b79db836-09ec-4244-ad48-caf6e9175bc0",
            "sourceColumn": "[Weekday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "acb1048b-0344-453a-8be5-fc9a773ed4f8",
            "sourceColumn": "[DayNo]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "df193394-84a9-4ce8-b402-4f6ed7f82897",
            "sourceColumn": "[DayMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f4fa065d-cc71-4aa1-82a1-385ddae4d0b2",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS(",
                "    CALENDAR(date(2017,01,01),date(2026,12,31)),",
                "        \"DateAsInteger\", FORMAT ( [Date], \"YYYYMMDD\" ), ",
                "        \"Year\", FORMAT([Date], \"yyyy\"), ",
                "        \"Year less 1\", FORMAT([Date], \"yyyy\")-1,",
                "        \"MonthYear\", FORMAT([Date],\"mmm yy\"),",
                "        \"QuarterYear\", FORMAT([Date],\"yyyy \\QQ\"), ",
                "        \"MonthNo\", MONTH([Date]),",
                "        \"MonthText\", FORMAT([Date], \"mmm\"),",
                "        \"YearMonth\", FORMAT([Date], \"MMMM-YYYY\"),",
                "        \"YMInt\", 13 * YEAR([Date]) + MONTH([Date]),",
                "        \"WeekdayNo\", WEEKDAY([Date],2),",
                "        \"Year & Month\", FORMAT([Date],\"MMM-YY\"),",
                "        \"Month\", FORMAT([Date], \"mmmm\"), ",
                "        \"WeekNo\", WEEKNUM([Date]),",
                "        \"EOW - Saturday\", [Date]+7-WEEKDAY([Date]-7),",
                "        \"Weekday\", FORMAT([Date], \"dddd\"), ",
                "        \"DayNo\", FORMAT([Date], \"d\"),",
                "        \"DayMonth\", FORMAT([Date], \"dd mmm\")",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2a7574a0-7be7-40b5-a9f8-174db5a82dd5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "51f88e71-466c-447f-adb9-58f5a997df34",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8214ff79-9983-490a-93a0-09d3a9f8376a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0bdb1e7e-9a08-41b2-ae80-746ea577e128",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "91058259-c450-4cae-9ed8-5c8b809dca10",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3a846061-efb6-4828-b818-05d857a00abe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4c468560-f38b-463b-8e9e-1a0650e666ee",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "31aa3407-4cd2-4a05-9a3b-205c1c8426e6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "707a1a12-f172-42e6-8967-ebb77d52d1ee",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c42bf963-fd5a-4648-9212-f60876bca951",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b698bf71-53fc-4a41-9ca3-ea1bd53aaa01",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e0e8619d-1b22-4496-9a8f-5b08ef31c5c7",
                "ordinal": 3
              }
            ],
            "lineageTag": "a8363ded-b11e-43e0-9ecf-0577da4d78b5"
          }
        ],
        "isHidden": true,
        "lineageTag": "e2a2e332-7591-444b-98a3-dd51bbaae7b3",
        "partitions": [
          {
            "name": "LocalDateTable_2a7574a0-7be7-40b5-a9f8-174db5a82dd5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('snowball_output'[month_roll])), 1, 1), Date(Year(MAX('snowball_output'[month_roll])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7d85d6a6-0015-4fa3-b1a9-faf8adb8e469",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8e80061d-c151-4d9a-818f-357dcb59a5f0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b3f9e452-49bb-4afe-8c3f-d6e3dc50e557",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a6496206-efd3-4258-bd48-a7ce6aae6391",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "011d7fe8-ea15-42f6-94e9-39f579091867",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b42e3259-de1a-43d8-87d2-1dd8502c10b3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "15521dbd-fd00-44e7-94ed-f643863515d1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea374e36-5554-4cd5-950a-9ef0f59ecc44",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f1546617-a48c-48af-8e74-c02932e41bd8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "09ee5b20-b926-4097-b762-2c2838c3cb87",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d723ad73-f510-4229-832e-059e346ed2b9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "09dc9fdc-aa07-468d-b302-bc82b686ed97",
                "ordinal": 3
              }
            ],
            "lineageTag": "3bd7d2b7-e51a-4fdb-9860-47f987fb1d19"
          }
        ],
        "isHidden": true,
        "lineageTag": "72d45810-d6ae-430f-b8db-4411997ed007",
        "partitions": [
          {
            "name": "LocalDateTable_7d85d6a6-0015-4fa3-b1a9-faf8adb8e469",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f9d24481-c760-4503-9a10-5941e087c86a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8781e599-69b5-4946-8aa2-4913a157ce39",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d96aaee6-89d8-4e25-92fb-708cfeda8ed6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6bae32b4-bec8-4478-a92f-a3c00938e528",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d75039ff-edbe-47a3-9820-c3e6bdbcaad4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "28a3ecf2-db8a-4831-a5e6-fd49508c0b49",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "961ab661-a496-4665-a62d-e32a0a9ee157",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "95882fd7-2fcc-4f94-bf5e-8a509f1aa177",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8eb8a98c-308a-4d9a-b16e-2dbb64340f33",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "96638c9a-966e-4b6b-b4fd-34e993b573d7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bb44a5aa-fd06-4326-95aa-b6f28c9a925e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ec54929d-3887-4c46-b890-6c3c9a287c54",
                "ordinal": 3
              }
            ],
            "lineageTag": "ab360666-f2dc-4379-a028-c3e68f167af4"
          }
        ],
        "isHidden": true,
        "lineageTag": "054910db-6446-427e-b05e-a1e0b0c260eb",
        "partitions": [
          {
            "name": "LocalDateTable_f9d24481-c760-4503-9a10-5941e087c86a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[EOW - Saturday])), 1, 1), Date(Year(MAX('Calendar'[EOW - Saturday])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}